public class CalcLogic extends javax.swing.JFrame {

    /**
     * Creates new form CalcLogic
     */
    public CalcLogic() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void atomicMass(String[] input){
        if (input[0] == null){
            return;
        }
        double total = 0;
        String disp = "";
        for (String i: input){
            Element temp = ElementHolder.stringToElement(i);
            total += (double)temp.getMass();
            disp += i;
        }
        javax.swing.JOptionPane.showMessageDialog(null, "The mass of "+ disp + " is " + total, "Formula Mass", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        //return total;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}