public class ChemCalc extends javax.swing.JFrame {

    /**
     * Creates new form ChemCalc
     */
    public ChemCalc() {
        initComponents();
        allClear();
        updateDisplay();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Display = new javax.swing.JTextField();
        buttonTable = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        showOnTop = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Display.setBackground(new java.awt.Color(204, 204, 255));
        Display.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        Display.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Display.setMargin(new java.awt.Insets(15, 6, 15, 6));
        getContentPane().add(Display, java.awt.BorderLayout.PAGE_START);

        buttonTable.setBackground(new java.awt.Color(204, 204, 255));
        buttonTable.setMaximumSize(new java.awt.Dimension(1000, 225));
        buttonTable.setMinimumSize(new java.awt.Dimension(1000, 225));
        buttonTable.setPreferredSize(new java.awt.Dimension(1000, 225));
        buttonTable.setLayout(new java.awt.GridBagLayout());

        jButton1.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jButton1.setText("H");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton1.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton1.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        buttonTable.add(jButton1, new java.awt.GridBagConstraints());

        jLabel1.setMaximumSize(new java.awt.Dimension(825, 50));
        jLabel1.setMinimumSize(new java.awt.Dimension(825, 50));
        jLabel1.setPreferredSize(new java.awt.Dimension(825, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 17;
        buttonTable.add(jLabel1, gridBagConstraints);

        jButton2.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jButton2.setText("He");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton2.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton2.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        buttonTable.add(jButton2, new java.awt.GridBagConstraints());

        jButton3.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jButton3.setText("Li");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton3.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton3.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        buttonTable.add(jButton3, gridBagConstraints);

        jButton4.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jButton4.setText("Be");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton4.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton4.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        buttonTable.add(jButton4, gridBagConstraints);

        jLabel2.setMaximumSize(new java.awt.Dimension(525, 50));
        jLabel2.setMinimumSize(new java.awt.Dimension(525, 50));
        jLabel2.setPreferredSize(new java.awt.Dimension(525, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 11;
        buttonTable.add(jLabel2, gridBagConstraints);

        jButton5.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jButton5.setText("B");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton5.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton5.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        buttonTable.add(jButton5, gridBagConstraints);

        jButton6.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jButton6.setText("C");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton6.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton6.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        buttonTable.add(jButton6, gridBagConstraints);

        jButton7.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jButton7.setText("N");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton7.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton7.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        buttonTable.add(jButton7, gridBagConstraints);

        jButton8.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jButton8.setText("O");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton8.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton8.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        buttonTable.add(jButton8, gridBagConstraints);

        jButton9.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jButton9.setText("F");
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton9.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton9.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        buttonTable.add(jButton9, gridBagConstraints);

        jButton10.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jButton10.setText("Ne");
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton10.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton10.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        buttonTable.add(jButton10, gridBagConstraints);

        jButton11.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jButton11.setText("Na");
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton11.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton11.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        buttonTable.add(jButton11, gridBagConstraints);

        jButton12.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jButton12.setText("Mg");
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton12.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton12.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        buttonTable.add(jButton12, gridBagConstraints);

        jLabel3.setMaximumSize(new java.awt.Dimension(525, 50));
        jLabel3.setMinimumSize(new java.awt.Dimension(525, 50));
        jLabel3.setPreferredSize(new java.awt.Dimension(525, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 11;
        buttonTable.add(jLabel3, gridBagConstraints);

        jButton13.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jButton13.setText("Al");
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton13.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton13.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton13.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        buttonTable.add(jButton13, gridBagConstraints);

        jButton14.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jButton14.setText("Si");
        jButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton14.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton14.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton14.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        buttonTable.add(jButton14, gridBagConstraints);

        jButton15.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jButton15.setText("P");
        jButton15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton15.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton15.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton15.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        buttonTable.add(jButton15, gridBagConstraints);

        jButton16.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jButton16.setText("S");
        jButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton16.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton16.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton16.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        buttonTable.add(jButton16, gridBagConstraints);

        jButton17.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jButton17.setText("Cl");
        jButton17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton17.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton17.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton17.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        buttonTable.add(jButton17, gridBagConstraints);

        jButton18.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jButton18.setText("Ar");
        jButton18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton18.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton18.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton18.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        buttonTable.add(jButton18, gridBagConstraints);

        jButton19.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jButton19.setText("K");
        jButton19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton19.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton19.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton19.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        buttonTable.add(jButton19, gridBagConstraints);

        jButton20.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jButton20.setText("Ca");
        jButton20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton20.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton20.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton20.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        buttonTable.add(jButton20, gridBagConstraints);

        jButton21.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jButton21.setText("Sc");
        jButton21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton21.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton21.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton21.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        buttonTable.add(jButton21, gridBagConstraints);

        jLabel4.setMaximumSize(new java.awt.Dimension(25, 50));
        jLabel4.setMinimumSize(new java.awt.Dimension(25, 50));
        jLabel4.setPreferredSize(new java.awt.Dimension(25, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        buttonTable.add(jLabel4, gridBagConstraints);

        jButton22.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jButton22.setText("Ti");
        jButton22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton22.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton22.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton22.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        buttonTable.add(jButton22, gridBagConstraints);

        jButton23.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jButton23.setText("V");
        jButton23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton23.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton23.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton23.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        buttonTable.add(jButton23, gridBagConstraints);

        jButton24.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jButton24.setText("Cr");
        jButton24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton24.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton24.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton24.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        buttonTable.add(jButton24, gridBagConstraints);

        jButton25.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jButton25.setText("Mn");
        jButton25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton25.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton25.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton25.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        buttonTable.add(jButton25, gridBagConstraints);

        jButton26.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jButton26.setText("Fe");
        jButton26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton26.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton26.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton26.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        buttonTable.add(jButton26, gridBagConstraints);

        jButton27.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jButton27.setText("Co");
        jButton27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton27.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton27.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton27.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        buttonTable.add(jButton27, gridBagConstraints);

        jButton28.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jButton28.setText("Ni");
        jButton28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton28.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton28.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton28.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        buttonTable.add(jButton28, gridBagConstraints);

        jButton29.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jButton29.setText("Cu");
        jButton29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton29.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton29.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton29.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        buttonTable.add(jButton29, gridBagConstraints);

        jButton30.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jButton30.setText("Zn");
        jButton30.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton30.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton30.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton30.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        buttonTable.add(jButton30, gridBagConstraints);

        jButton31.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jButton31.setText("Ga");
        jButton31.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton31.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton31.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton31.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        buttonTable.add(jButton31, gridBagConstraints);

        jButton32.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jButton32.setText("Ge");
        jButton32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton32.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton32.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton32.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        buttonTable.add(jButton32, gridBagConstraints);

        jButton33.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jButton33.setText("As");
        jButton33.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton33.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton33.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton33.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        buttonTable.add(jButton33, gridBagConstraints);

        jButton34.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jButton34.setText("Se");
        jButton34.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton34.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton34.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton34.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        buttonTable.add(jButton34, gridBagConstraints);

        jButton35.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jButton35.setText("Br");
        jButton35.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton35.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton35.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton35.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        buttonTable.add(jButton35, gridBagConstraints);

        jButton36.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jButton36.setText("Kr");
        jButton36.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton36.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton36.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton36.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        buttonTable.add(jButton36, gridBagConstraints);

        jButton37.setText("back");
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        buttonTable.add(jButton37, new java.awt.GridBagConstraints());

        getContentPane().add(buttonTable, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuItem1.setText("Quit");
        jMenuItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Options");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        showOnTop.setText("Show on top");
        showOnTop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showOnTop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleAlwaysShow(evt);
            }
        });
        jMenu2.add(showOnTop);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcButtonPressed
        // TODO add your handling code here:
        onButtonPressed((javax.swing.JButton)evt.getSource());
    }//GEN-LAST:event_calcButtonPressed

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_quitActionPerformed

    private void toggleAlwaysShow(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleAlwaysShow
        // TODO add your handling code here:
        if(showOnTop.isSelected()){
            setAlwaysOnTop(true);
        }
        else{
            setAlwaysOnTop(false);
        }
    }//GEN-LAST:event_toggleAlwaysShow
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChemCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChemCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChemCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChemCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChemCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Display;
    private javax.swing.JPanel buttonTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JCheckBoxMenuItem showOnTop;
    // End of variables declaration//GEN-END:variables

    private String disp;
    
    private void handlePress(String item){
        if (item.equals("clear")){
            allClear();
        }
        else if (item.equals("back")){
            backspace(); //TODO: Go back a character
        }
        else{
            disp = disp + item;
            //System.out.println(inputHandler.atomicMass(ElementHolder.stringToElement(inputHandler.splitInput(disp))));
        }
        
    }
    
    private void allClear(){
        disp = "";
    }
    
    private void backspace(){
        String[] oldText = inputHandler.splitInput(disp);
        System.out.println(oldText.length);
        String newText = "";
        if (oldText.length == 1){
            allClear();
            return;
        }
        for (int i = 0; i < oldText.length-1; i++){
            newText = newText + oldText[i];
        }
        disp = newText;
    }
    
    private void updateDisplay(){
        if (disp.length() > 0){
            Display.setText(disp);
        }
        //else  ()
    }
    
    private void onButtonPressed(javax.swing.JButton button){
        //System.out.println(button.getText());
        //System.out.println(disp);
        handlePress(button.getText());
        updateDisplay();
        //inputHandler.splitInput(disp);
        
    }

}